"use client";

import { Header } from "@/components/ui/header-2";
import { Footer } from "@/components/ui/footer";
import { InfiniteGridBg } from "@/components/ui/infinite-grid-bg";

const SUPPORT_EMAIL = "support@browsersky.dev";

const sections = [
  {
    title: "1. Acceptance of Terms",
    content: `By installing, accessing, or using the BrowserSky AI Chrome extension or website (collectively, the "Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.`,
  },
  {
    title: "2. Description of Service",
    content: `BrowserSky AI is a Chrome browser extension that opens a side panel allowing you to ask questions about the current webpage you are viewing. When you interact with the extension, it reads the visible text content of the active tab (up to 50,000 characters), or captures a screenshot for complex web applications, and sends that content along with your question to our backend servers, which then call third-party AI model providers to generate a response.`,
  },
  {
    title: "3. User Accounts",
    content: `You must create an account to use the Service. Accounts are managed via Clerk, a third-party authentication provider. You are responsible for maintaining the confidentiality of your credentials and for all activity that occurs under your account. You must be at least 13 years old to create an account. We reserve the right to terminate accounts that violate these Terms.`,
  },
  {
    title: "4. Subscription Plans & Credits",
    content: `The Service uses a credit-based system.\n\nFree Tier: 50 credits per day, resetting every 24 hours. Restricted to budget AI models.\n\nPro Tier: 2,000 credits per month, resetting every 30 days. Access to all available AI models.\n\nCredit costs per query vary by model:\n• GPT-4o-mini, Grok-3-mini, MiniMax: 1 credit\n• Claude Haiku: 3 credits\n• GPT-4o: 6 credits\n• Claude Sonnet, Grok-3: 8 credits\n\nCredits do not roll over. Unused credits at the end of a billing period are forfeited.`,
  },
  {
    title: "5. Billing & Refunds",
    content: `Pro subscriptions are billed through LemonSqueezy, our third-party payment processor. Subscription pricing is $20.00 per month, or approximately $13.00 per month when billed annually ($156.00/year).\n\nAll sales are final. We do not offer refunds for unused credits, partial billing periods, or subscription cancellations unless required by applicable law. You may cancel your subscription at any time; access to Pro features continues until the end of the current billing period.`,
  },
  {
    title: "6. Data We Access & Store",
    content: `To provide the Service, the extension accesses the following data:\n\nPage Content: When you submit a question, the extension extracts the visible text (title, URL, and body text up to 50,000 characters) from your active browser tab. For certain complex applications (e.g., Google Docs, Figma, Notion, Canva, Miro, Linear, Asana, Trello, LinkedIn editors), a JPEG screenshot is captured instead.\n\nConversation History: Your question and response history for the current tab is kept in the extension's service worker memory during that browser session. This history is lost when the browser is closed or the extension is reloaded.\n\nStored in Chrome Storage:\n• Your Clerk authentication token (local, persistent)\n• Your name, email address, and profile image URL (local, persistent)\n• Your current credit balance, credit reset timestamp, and subscription tier (local, persistent)\n• Cached page context per tab (session only, cleared when the tab is closed)\n\nWe do not sell your personal data. Page content and conversation data sent to our backend is used solely to generate your AI response and is processed by third-party AI providers as described in Section 8.`,
  },
  {
    title: "7. Browser Permissions",
    content: `BrowserSky AI requests the following Chrome permissions, each required for the Service to function:\n\n• Access to all websites (<all_urls>): Required to read page content from any site you choose to analyze.\n• Active tab, tabs, scripting: Required to inject the content extraction script into the current tab and retrieve page text or take screenshots.\n• Storage: Required to persist your account token, credit balance, and tier between browser sessions.\n• Side panel: Required to render the AI chat interface in Chrome's built-in side panel.\n• Tab groups: Used to visually group tabs under "BrowserSky AI" when relevant.`,
  },
  {
    title: "8. Third-Party AI Providers",
    content: `Responses are generated by one of the following third-party AI model providers, depending on the model you select:\n\n• OpenAI (GPT-4o, GPT-4o-mini) — openai.com\n• Anthropic (Claude Sonnet, Claude Haiku) — anthropic.com\n• xAI (Grok-3, Grok-3-mini) — x.ai\n• MiniMax (MiniMax-Text-01) — minimaxi.com\n\nBy using the Service, you acknowledge that your queries and page content are transmitted to these providers and are subject to their respective terms of service and privacy policies. We do not control how these providers handle data on their end.`,
  },
  {
    title: "9. Prohibited Uses",
    content: `You agree not to:\n\n• Use the Service for any unlawful purpose or in violation of any applicable laws or regulations.\n• Attempt to reverse-engineer, decompile, or extract the source code of the Service.\n• Use automated scripts or bots to interact with the Service or generate queries.\n• Abuse the credit system, share accounts, or attempt to circumvent usage limits.\n• Submit content that is harmful, abusive, threatening, defamatory, or infringes on any third-party rights.\n• Use the Service to collect or harvest data from websites in violation of those sites' terms of service.`,
  },
  {
    title: "10. Intellectual Property",
    content: `BrowserSky AI and its underlying technology, branding, and website content are owned by us and protected by applicable intellectual property laws. You retain ownership of any content you create or submit. By using the Service, you grant us a limited, non-exclusive license to process your submitted content solely for the purpose of delivering the Service to you.`,
  },
  {
    title: "11. Disclaimer of Warranties",
    content: `THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR THAT AI-GENERATED RESPONSES WILL BE ACCURATE, COMPLETE, OR SUITABLE FOR ANY PARTICULAR PURPOSE. AI MODELS CAN AND DO PRODUCE INCORRECT OR MISLEADING INFORMATION. YOU USE AI-GENERATED CONTENT AT YOUR OWN RISK.`,
  },
  {
    title: "12. Limitation of Liability",
    content: `TO THE MAXIMUM EXTENT PERMITTED BY LAW, BROWSERSKY AI AND ITS OPERATORS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF DATA, REVENUE, OR PROFITS, ARISING OUT OF OR RELATED TO YOUR USE OF THE SERVICE. OUR TOTAL LIABILITY FOR ANY CLAIM ARISING UNDER THESE TERMS SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE 3 MONTHS PRECEDING THE CLAIM.`,
  },
  {
    title: "13. Termination",
    content: `We may suspend or terminate your account at any time for violations of these Terms or for any other reason at our discretion, with or without notice. You may stop using the Service and delete your account at any time by contacting us at the email address below. Upon termination, your stored data will be deleted in accordance with our data retention practices.`,
  },
  {
    title: "14. Changes to These Terms",
    content: `We may update these Terms of Service from time to time. When we do, we will update the "Last updated" date at the top of this page. Your continued use of the Service after changes are posted constitutes your acceptance of the updated Terms.`,
  },
  {
    title: "15. Contact",
    content: `If you have questions about these Terms, please contact us at:`,
  },
];

export default function TermsPage() {
  return (
    <div
      className="relative min-h-screen flex flex-col font-[family-name:var(--font-gelasio)]"
      style={{ background: "#0f1f27" }}
    >
      <div className="relative flex-1">
        <InfiniteGridBg />
        <Header />
        <main className="px-6 pt-36 pb-24">
          <div className="max-w-3xl mx-auto">
            {/* Title */}
            <h1 className="text-3xl md:text-4xl font-semibold text-white mb-2">
              Terms of Service
            </h1>
            <p className="text-white/30 text-sm mb-12">
              Last updated: March 15, 2026
            </p>

            {/* Sections */}
            <div className="flex flex-col gap-10">
              {sections.map((section) => (
                <div key={section.title}>
                  <h2 className="text-base font-semibold text-white mb-3">
                    {section.title}
                  </h2>
                  {section.content.split("\n").map((line, i) =>
                    line === "" ? (
                      <div key={i} className="h-3" />
                    ) : (
                      <p
                        key={i}
                        className="text-white/55 text-sm leading-relaxed"
                      >
                        {line}
                      </p>
                    )
                  )}
                  {section.title.startsWith("15.") && (
                    <a
                      href={`mailto:${SUPPORT_EMAIL}`}
                      className="inline-block mt-2 text-sm text-white/70 hover:text-white underline underline-offset-2 transition-colors"
                    >
                      {SUPPORT_EMAIL}
                    </a>
                  )}
                </div>
              ))}
            </div>
          </div>
        </main>
      </div>
      <Footer />
    </div>
  );
}
